name: Test

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        go-version: ['1.18']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone and checkout branch
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: make test